package jonatan.andrei.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum RecommendationSettingsType {

    QUESTION_LIST_NUMBER_OF_DAYS_QUESTION_IS_RECENT(7),
    QUESTION_LIST_NUMBER_OF_DAYS_QUESTION_IS_RELEVANT(365),
    QUESTION_LIST_MINIMUM_OF_ACTIVITIES_TO_CONSIDER_MAXIMUM_SCORE(10),
    QUESTION_LIST_RELEVANCE_PUBLICATION_DATE_RECENT(100),
    QUESTION_LIST_RELEVANCE_PUBLICATION_DATE_RELEVANT(100),
    QUESTION_LIST_RELEVANCE_UPDATE_DATE_RECENT(50),
    QUESTION_LIST_RELEVANCE_HAS_ANSWER(-30), //
    QUESTION_LIST_RELEVANCE_NUMBER_ANSWERS(-10), //
    QUESTION_LIST_RELEVANCE_HAS_BEST_ANSWER(-50), //
    QUESTION_LIST_RELEVANCE_DUPLICATE_QUESTION(-100), //
    QUESTION_LIST_RELEVANCE_NUMBER_VIEWS(3), //
    QUESTION_LIST_RELEVANCE_NUMBER_FOLLOWERS(10), //
    QUESTION_LIST_RELEVANCE_NUMBER_UPVOTES(10), //
    QUESTION_LIST_RELEVANCE_NUMBER_DOWNVOTES(-10), //
    QUESTION_LIST_RELEVANCE_USER_ALREADY_ANSWERED(-20), //
    QUESTION_LIST_RELEVANCE_USER_ALREADY_COMMENTED(-20), //
    QUESTION_LIST_RELEVANCE_USER_FOLLOWER_ASKER(100), //
    QUESTION_LIST_RELEVANCE_USER_ALREADY_VIEWED(-20), //
    QUESTION_LIST_RELEVANCE_USER_ALREADY_VIEWED_IN_LIST(-15), //
    QUESTION_LIST_RELEVANCE_USER_ALREADY_VIEWED_IN_EMAIL(-15), //
    QUESTION_LIST_RELEVANCE_USER_ALREADY_VIEWED_IN_NOTIFICATION(-30), //
    QUESTION_LIST_RELEVANCE_EXPLICIT_CATEGORY(100), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_ASKED_IN_CATEGORY(50), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_ANSWERED_IN_CATEGORY(100), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_COMMENTED_IN_CATEGORY(50), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_VIEWED_IN_CATEGORY(100), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_FOLLOWED_IN_CATEGORY(50), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_UPVOTED_IN_CATEGORY(50), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_DOWNVOTED_IN_CATEGORY(-5), //
    QUESTION_LIST_RELEVANCE_ANSWERS_UPVOTED_IN_CATEGORY(50), //
    QUESTION_LIST_RELEVANCE_ANSWERS_DOWNVOTED_IN_CATEGORY(-5), //
    QUESTION_LIST_RELEVANCE_COMMENTS_UPVOTED_IN_CATEGORY(20), //
    QUESTION_LIST_RELEVANCE_COMMENTS_DOWNVOTED_IN_CATEGORY(-2), //
    QUESTION_LIST_RELEVANCE_EXPLICIT_TAG(100),
    QUESTION_LIST_RELEVANCE_QUESTIONS_ASKED_IN_TAG(50),
    QUESTION_LIST_RELEVANCE_QUESTIONS_ANSWERED_IN_TAG(100),
    QUESTION_LIST_RELEVANCE_QUESTIONS_COMMENTED_IN_TAG(50), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_VIEWED_IN_TAG(100), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_FOLLOWED_IN_TAG(50), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_UPVOTED_IN_TAG(50), //
    QUESTION_LIST_RELEVANCE_QUESTIONS_DOWNVOTED_IN_TAG(-5), //
    QUESTION_LIST_RELEVANCE_ANSWERS_UPVOTED_IN_TAG(50), //
    QUESTION_LIST_RELEVANCE_ANSWERS_DOWNVOTED_IN_TAG(-5), //
    QUESTION_LIST_RELEVANCE_COMMENTS_UPVOTED_IN_TAG(20), //
    QUESTION_LIST_RELEVANCE_COMMENTS_DOWNVOTED_IN_TAG(-2); //

    private Integer defaultValue;
}
