package jonatan.andrei.domain;

public enum UserActionType {

    QUESTION_ASKED,
    QUESTION_VIEWED,
    QUESTION_ANSWERED,
    QUESTION_COMMENTED,
    QUESTION_FOLLOWED,
    QUESTION_UPVOTED,
    QUESTION_DOWNVOTED,
    ANSWER_UPVOTED,
    ANSWER_DOWNVOTED,
    COMMENT_UPVOTED,
    COMMENT_DOWNVOTED

}
